dist: xenial
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO="Django>=2.2,<3.0" DB=sqlite
  - DJANGO="Django>=3.0,<3.1" DB=sqlite
jobs:
  include:
    - stage: codestyle
      python: 3.9
      install:
        - pip install flake8 isort
      script:
        - flake8
        - isort --check-only .
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1" DB=sqlite
install:
  - export PYTHONPATH=./:$PYTHONPATH
  - pip install -U $DJANGO
  - pip install -r tests/requirements.txt
script:
  - python tests/manage.py test testapp
