# Generated by Django 2.2 on 2019-04-14 11:03

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ModelUploadToCallable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to=testapp.models.callable_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ModelUploadToString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='sample_subdir')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', testapp.models.MySlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithValidatedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.PositiveIntegerField(validators=[testapp.models.validate_even])),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='QObjectRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Redefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('char_field', models.CharField(max_length=5)),
                ('boolean_field', models.BooleanField()),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_field', models.EmailField(max_length=254)),
                ('float_field', models.FloatField()),
                ('integer_field', models.IntegerField()),
                ('ip_field', models.GenericIPAddressField()),
                ('null_boolead_field', models.NullBooleanField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('small_integer', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('file_field', models.FileField(upload_to='sample_subdir')),
                ('image_field', models.ImageField(upload_to='sample_subdir')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleModelWithDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField(default=8223372036854775807)),
                ('char_field', models.CharField(default='USSR', max_length=5)),
                ('boolean_field', models.BooleanField(default=True)),
                ('date_field', models.DateField(default=datetime.date(2010, 12, 10))),
                ('datetime_field', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=10)),
                ('email_field', models.EmailField(default='admin@dev.null', max_length=254)),
                ('float_field', models.FloatField(default=0.7)),
                ('integer_field', models.IntegerField(default=42)),
                ('ip_field', models.GenericIPAddressField(default='127.0.0.1')),
                ('null_boolead_field', models.NullBooleanField(default=None)),
                ('positive_integer_field', models.PositiveIntegerField(default=4)),
                ('small_integer', models.PositiveSmallIntegerField(default=1)),
                ('slug_field', models.SlugField(default='any_model_default')),
                ('text_field', models.TextField(default='Lorem ipsum')),
                ('time_field', models.TimeField(default=datetime.time(11, 14))),
                ('url_field', models.URLField(default='http://yandex.ru')),
            ],
        ),
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SelfReferencingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.SelfReferencingModel')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipModelsWithDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_fk', to='testapp.TargetModel')),
                ('o2o', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_o2o', to='testapp.TargetModel')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedToRedefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Redefined')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedToQObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.QObjectRelated')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithOneToOneField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.OneToOneRelated')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithGenericRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithConstraintOnForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ModelWithConstraint')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.RelatedModel')),
            ],
        ),
    ]
